microsoft/DMF

Dmf/Framework/DmfCore.c, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h
Correct issue where Child Modules that are ancestors of Dynamic Modules were not opened.
=> Child Module of Dynamic Module.

DmfSamples/SwitchBar/DmfInterface.c, DmfSamples/SwitchBar/README.md, DmfSamples/SwitchBar/trace.h, DmfSamples/SwitchBar2/DmfInterface.c, DmfSamples/SwitchBar2/README.md, DmfSamples/SwitchBar2/trace.h, DmfSamples/SwitchBar3/DmfInterface.c, DmfSamples/SwitchBar3/README.md, DmfSamples/SwitchBar3/trace.h, DmfSamples/SwitchBar4/DmfInterface.c, DmfSamples/SwitchBar4/README.md, DmfSamples/SwitchBar4/trace.h
Add WPP tracing to the samples. This shows how to emit WPP tracing from Modules as well as the Client driver.
=> Add WPP tracing to the samples.

Dmf/Framework/DmfContainer.c, Dmf/Framework/DmfGeneric.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/DmfInternal.c, Dmf/Framework/DmfModuleCollection.c
Fix asserts that happen with calls to DMF_Invoke_DeviceCallbacksCreate/DMF_Invoke_DeviceCallbacksDestroy/DMF_Invoke_DeviceCallbacksCreate.
Automatically call DMF_Invoke_DeviceCallbacksDestroy() when the Client is unable to.
=> Fix issues related to non-PnP drivers.

Dmf/Framework/DmfContainer.c, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfDeviceInit.c, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/Modules.Core/DmfModules.Core.Trace.h, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_HidTarget.h, Dmf/Modules.Library/Dmf_HidTarget.md, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
1. Correct bug in Dmf_NotifyUserWithRequest where decrement of held Requests happens after Request is returned instead of before. If Client immediately attempts to enqueue a Request in completion routine, it can fail improperly.
2. Correct issue with Dynamic Modules when they are Child Modules so that callbacks can access the Parent Module.
3. Add Method to Dmf_HidTarget to allow Client to read input reports synchronously. This is necessary for some kinds of devices.
4. Minor fixes to make compilation work with more compilers and environments.
NOTE: It is not clear to me why diffs seem to think whole file has changed.
=> Merge20192801

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfGeneric.c, Dmf/Framework/DmfHelpers.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_SerialTarget.c, Dmf/Modules.Library/Dmf_SerialTarget.h
Fix ModuleOpen and ModuleClose to not open Child Modules. (This code was not in use and should have been removed during a previous refactoring.)
Fix crash for Dynamic Modules using DMF features. (Using DMF Features from Dynamic Modules will be supported later.)
Update NotificationRegister validation.
Fix ContinuousRequestTarget invalid buffer access when no output buffers are used.
=> Merge20190429:

Dmf/Framework/Modules.Core/Dmf_BufferPool.c, Dmf/Modules.Library.Tests/Dmf_Tests_BufferPool.c, Dmf/Modules.Library.Tests/Dmf_Tests_BufferQueue.c, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_HashTable.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c, Dmf/Modules.Library.Tests/Dmf_Tests_RingBuffer.c, Dmf/Modules.Library.Tests/Dmf_Tests_SelfTarget.c, Dmf/Modules.Library.Tests/TestsUtility.c, Dmf/Modules.Library.Tests/TestsUtility.h, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_Pdo.md, DmfTest/DmfKTest/sys/DmfInterface.c, DmfTest/DmfKTest/sys/Trace.h
Merge20190516: 
1. Fix issue in DMF_ContinuousRequestTarget that could cause BSOD during Close due to race condition while deleting Requests that may be in use. (Close will not begin to execute until all asynchronous requests have been processed.)
2. Correct issue with Test Driver that caused many hidden PDOs to be left on test machine.
3. Several updates to Test Driver Modules to make it more robust and faster during disable of bus driver.
4. Correct issue in DMF_BufferPool where it incorrectly kept searching for a buffer in the list that was already found.
5. Correct issue in Hash Table tests because it was possible that duplicate keys could be randomly created (for different records).
6. Make cancellation logic more robust in Tests_IoctlHandler.
7. Correct some SAL issues in Test …
=> Merge20190516

Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c, Dmf/Modules.Library.Tests/Dmf_Tests_SelfTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c
1. Fix issue where DMF_ContinousRequestTarget incorrectly allows Client to create PASSIVE_LEVEL context buffers. This does not work because the completion routine that uses them always runs in DISPATCH_LEVEL.
2. Fix issues with cancellation due to WDF verifier rules in DMF_Tests_IoctlHandler.
=> Merge20190521

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfFilter.c, Dmf/Framework/Modules.Core/Dmf_BufferPool.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
1. Correct incorrect assert in DMF_BufferPool.
2. Correct issue causing assertion in some filter drivers.
3. Correct bug in User Mode related to auxiliary locks.
4. Correct issue where "remove cancel" callback happens before underlying target is open.
=> Merge20190528:

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfGeneric.c, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Modules.Library/Dmf_ScheduledTask.c, Dmf/Modules.Library/Dmf_String.c, Dmf/Modules.Library/Dmf_String.h, Dmf/Modules.Library/Dmf_String.md
1. Module Child List iteration is changed to to match the WDF callback iteration for the DMF tree. In some cases this allows for the Client to close down Modules more gracefully when Child Modules callback into the Parent Module during shutdown.
2. Add a Method for GUID comparison to DMF_String.
3. Make it possible to instantiate DMF_ScheduledTask dynamically.
4. Give access to a Module's Config data to a Client. This is useful in cases where the Client has instantiated multiple instances of the same Module and receives callbacks from those instances. Client can now access the caller's Config to know which instance is calling back.
=> Merge20190531

Dmf/Documentation/Driver Module Framework.md, Dmf/Framework/DmfCall.c, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/DmfModule.h, Dmf/Framework/DmfModuleCollection.c, Dmf/Modules.Library.Tests/Dmf_Tests_Registry.c, Dmf/Modules.Library.Tests/Dmf_Tests_Registry.h, Dmf/Modules.Library/Dmf_CmApi.c, Dmf/Modules.Library/Dmf_CmApi.h, Dmf/Modules.Library/Dmf_CmApi.md, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_Pdo.c, Dmf/Modules.Library/Dmf_Pdo.h, Dmf/Modules.Library/Dmf_Registry.c, Dmf/Modules.Library/Dmf_Registry.h, Dmf/Modules.Library/Dmf_Registry.md, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Modules.Library/Dmf_RequestTarget.h, Dmf/Modules.Library/Dmf_RequestTarget.md, Dmf/Modules.Library/Dmf_Thread.c, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.c
1. Add Methods to Dmf_Registry to allow Client to easily access predefined keys.
2. Add Methods to Dmf_CmApi to allow Client to get properties from target.
3. Changes to how Dynamic Modules are torn down to correct issues found during stress testing. Associated changes to Dmf_ContinuousRequestTarget to better support Dynamic instantiation.
4. Changes to Dmf_Pdo to allow Client to easily set properties of PDOs that are created.
5. Changes to Dmf_Thread and Dmf_ThreadedBufferQeueue to stop thread during tear down in case Client fails to do so.
7. Updates to Tests Modules to add tests.
8. Prevent compiler optimizations related to Module Config structures during Modules Add callback.
=> Merge20190730

Dmf/Framework/DmfCore.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/DmfUtility.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c, Dmf/Modules.Library/DmfModules.Library.h, Dmf/Modules.Library/Dmf_CmApi.c, Dmf/Modules.Library/Dmf_CmApi.h, Dmf/Modules.Library/Dmf_CmApi.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_I2cTarget.c, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c, Dmf/Modules.Library/Dmf_Rundown.c, Dmf/Modules.Library/Dmf_Rundown.h, Dmf/Modules.Library/Dmf_Rundown.md, Dmf/Modules.Library/Dmf_SpiTarget.c, Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj, Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
1. Correct BSOD during arrival/removal stress in DMF_DeviceInterfaceTarget.
2. Add Methods to DMF_CmApi.
3. Add DMF_Rundown.
4. Add DMF_I2cTarget to User-mode Library.
5. Correct a couple of issues where pointers to objects were not cleared after being deleted.
6. Correct issue in DMF_Tests_DeviceInteraceTarget where device arrival/removal callbacks were not set.
=> Merge20190816

Dmf/Modules.Library/Dmf_Thread.c
Correct regression caused by recent change to DMF_Thread. DMF_Thread_Start after DMF_Thread_Stop issue.
=> Merge20191111

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfInternal.c, Dmf/Framework/Modules.Core/Dmf_BufferPool.c
Perform buffer overrun checking in Release buidl when Verifier is enabled.
Make it easier to debug Module Open/RegisterNotification failures.
Both these changes are non-functional.
=> Merge20191120

Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_QueuedWorkItem.md
Per feedback, correct assert in a way that allows use of Reinitialize to illustrate better pattern for rundown APIs.
=> Merge20191121

Dmf/Documentation/Driver Module Framework.md, Dmf/Framework/DmfCall.c, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfPortable.c, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library/Dmf_AlertableSleep.c, Dmf/Modules.Library/Dmf_ComponentFirmwareUpdate.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_QueuedWorkItem.c, Dmf/Modules.Library/Dmf_Thread.c, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.c, Dmf/Modules.Library/Dmf_VirtualHidKeyboard.c
1. Update portable event API to simply and clean up and make sure all status are translated correctly.
2. Enforce that locks are released by acquiring thread. An incorrect API was used to get the thread id previously (in User-mode).
3. Fix event handle leak in User-mode.
=> Merge20200103

Dmf/Documentation/Driver Module Framework.md, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfFilter.c, Dmf/Framework/DmfModule.h
1. Give Client drivers access to DMF_ModuleReference() and DMF_ModuleDereference().
2. Ensure that only a single Control Device is created for filter drivers.
=> Merge20200206

Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfPortable.c, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h, Dmf/Modules.Library/Dmf_DefaultTarget.c, Dmf/Modules.Library/Dmf_DefaultTarget.h, Dmf/Modules.Library/Dmf_DefaultTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_Registry.c, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Modules.Library/Dmf_RequestTarget.h, DmfTest/DmfKTest/sys/DmfInterface.c
Merge20200302
1. Add support for cancelling asynchronous requests.
2. Correct issue in DMF_Registry which caused failure in cases when WDFDEVICE is set to synchronous operation.
3. Merge some SAL fixes.
4. Merge a fix in DMF_Portable_EventWaitForSingleObject when timeout value is set in User-mode.
=> Merge20200302

Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.md, Dmf/Modules.Library/Dmf_DefaultTarget.c, Dmf/Modules.Library/Dmf_DefaultTarget.h, Dmf/Modules.Library/Dmf_DefaultTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Modules.Library/Dmf_RequestTarget.h, Dmf/Modules.Library/Dmf_RequestTarget.md
Remove improperly exposed parameter from Client API for DMF_*Target. Requires change to Client drivers to simply remove the parameter from the call.
=> Merge20200319.1

Dmf/Framework/DmfCore.c, Dmf/Framework/DmfFilter.c, Dmf/Framework/DmfPortable.c, Dmf/Framework/DmfTrace.h, Dmf/Framework/DmfUtility.c, Dmf/Framework/Modules.Core/DMF_String.c, Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c, Dmf/Framework/Modules.Core/Dmf_RingBuffer.c, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library/Dmf_AlertableSleep.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.md, Dmf/Modules.Library/Dmf_DefaultTarget.c, Dmf/Modules.Library/Dmf_DefaultTarget.h, Dmf/Modules.Library/Dmf_DefaultTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Modules.Library/Dmf_RequestTarget.h, Dmf/Modules.Library/Dmf_RequestTarget.md, DmfTest/DmfKTest/sys/Trace.h, DmfTest/DmfUTest/sys/trace.h
1. Fix race condition in cancel path of ..._Cancel() in DMF_RequestTarget and DMF_ContinuousRequestTarget.
2. Fix related issue when the WDFREQUEST handle values are reused.
3. Update documentation for the above two items.
4. Update Unit Test Modules to add more tests including tests that test more possible cancel paths.
5. Remove spurious logging from several Modules.
6. Update some compile time inclusion code to support further work.
7. Update trace GUIDs in Test Driver.
=> Merge20200421

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfModule.h, Dmf/Framework/Modules.Core/Dmf_BufferPool.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.md
1. Instantiate Child DMF_BufferPool Module as DISPATCH_LEVEL by default in DMF_ContinuousRequestTarget even if the Parent is instantiated as PASSIVE_LEVEL so that its Methods can be called at DISPATCH_LEVEL.
2. Convert the verification check in DMF_BufferPool which was only in DEBUG build to a check done always using Verifier.
3. Update documentation to explain the above change.
(Previously, the mode of the Child BufferPool was the same as its Parent, ContinuousRequestTarget.)
=> Merge20200423

Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_AcpiTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
1. Correct regression in Surprise-removal path caused by recent remove cancel fix.
2. Update status code return value.
3. Update unit tests for DMF_DeviceInterfaceTarget so that surprise removal can be more easily tested.
=> Merge20200428

Dmf/Modules.Library.Tests/Dmf_Tests_BufferQueue.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_Registry.c, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
1. Correct synchronization issues in QueryRemove/RemoveCancel/RemoveComplete path in DMF_DeviceInterfaceTarget.
2. Properly clear a the QueryRemoveHappened flag in DMF_DeviceInterfaceMulitpleTarget.
3. Correct issue in DMF_ContinuousRequestTarget and DMF_RequestTarget where request id was improperly read from the request context after the request was sent. Applicable only to SendEx() API. 
4. Correct bug in DMF_Tests_IoctlHandler (unit test code) related to request cancellation (verifier issue). (Test code bug.)
5. Add missing DMF_Rundown to User-mode Library. (New feature.)
6. Correct two issues in unit test code in DMF_Tests_Registry and DMF_Tests_BufferQueue. (Test code bug.)
7. Update units test code in DMF_Test_DeviceInterfaceTarget to add case for non-attached IoTarget. (New test …
=> Merge20200515

Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Framework/DmfIncludes_USER_MODE.h, Dmf/Framework/Modules.Core/DMF_String.c, Dmf/Modules.Library.Tests/Dmf_Tests_AlertableSleep.c, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c, Dmf/Modules.Library.Tests/Dmf_Tests_SelfTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_Pdo.c, Dmf/Modules.Library/Dmf_Pdo.h, Dmf/Modules.Library/Dmf_Pdo.md, Dmf/Modules.Library/Dmf_RequestTarget.c, Dmf/Modules.Library/Dmf_ScheduledTask.c, DmfSamples/kmdf_fx2_dmf/driver_dmf_1/osrusbfx2dmf1.vcxproj, DmfSamples/kmdf_fx2_dmf/driver_dmf_1/osrusbfx2dmf1.vcxproj.Filters, DmfSamples/kmdf_fx2_dmf/driver_dmf_2/osrusbfx2dmf2.vcxproj, DmfSamples/kmdf_fx2_dmf/driver_dmf_2/osrusbfx2dmf2.vcxproj.Filters, DmfSamples/kmdf_fx2_dmf/driver_dmf_3/osrusbfx2dmf3.vcxproj, DmfSamples/kmdf_fx2_dmf/driver_dmf_3/osrusbfx2dmf3.vcxproj.Filters, DmfSamples/kmdf_fx2_dmf/driver_dmf_4/osrusbfx2dmf4.vcxproj, DmfSamples/kmdf_fx2_dmf/driver_dmf_4/osrusbfx2dmf4.vcxproj.Filters
Merge20200616
1. Correct BSOD in DMF_RequestTarget when it is used in PASSIVE_LEVEL mode due to paged pool context buffers.
2. Correct possible lock up during asynchronous removal in DMF_DeviceIntefaceMultipleTarget.
3. Add ability to use default (-1) address when creating a PDO in DMF_Pdo. This corrects and issue where a PDO will be improperly associated with an unrelated ACPI device.
4. Add DmfBreak() API so that hard breakpoints can easily set when debugging Kernel and User-mode code.
5. Correct several issues in Unit Test Modules and update the code so it is easier to test specific code paths on demand.
6. Remove some spurious logging that was filling up logging buffers.
7. MSVC keeps trying to update some of the project files so I finally gave in and just updated them. In a later PR …
=> Merge20200616

Dmf/Framework/Modules.Core/Dmf_HashTable.c, build/azure-pipelines.github.yml
1. Correct unparented memory allocation. (Benign issue because memory is explicitly freed.)
=> Merge20201002

Dmf/Framework/DmfCall.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_HidTarget.c
Merge20201029:
0. Add option to allow Client of DMF_DeviceInterfaceTarget to receive PreClose()/PostOpen() callbacks to ease porting of existing code. (This option should not be used by new code.)
1. Correct BSOD when a duplicate "QueryRemove" message appears.
2. Correct issue where NTSTATUS from Client is lost in a couple of callbacks.
3. Correct issue in HidTarget related to instack removal path.
=> Merge20201029

Dmf/Framework/DmfCall.c, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfIncludeInternal.h
Fix issue with framework using Module's lock to synchronize internal ReferenceCount.
Module's can be instantiated using either PASSIVE or DISPATCH level settings. However, the framework was using the Module's locks for synchronizing the ReferenceCount. This does not work in cases where a Module instantiated as PASSIVE  has Methods called from DISPATCH level that access the ReferenceCount.
The Module's reference count needs its own private lock which is a spinlock so it can be accessed from both PASSVIVE and DISPATCH levels.
DMF_ModuleReference() may be called from either PASSIVE or DISPATCH levels. This fix allows for that.
=> Merge20210118

Dmf/Documentation/Driver Module Framework.md
Changed nonexistent case-sensitive `WDF_IO_QUEUE_Config_INIT_DEFAULT_QUEUE` to `WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE` in the sample snippet of the documentation.
=> Fixed spelling in I/O queue hook example snippet

Dmf/DmfVersion.h, Dmf/Modules.Library/DmfModules.Library.h, Dmf/Modules.Library/Dmf_AcpiTarget.c, Dmf/Modules.Library/Dmf_AcpiTarget.h, Dmf/Modules.Library/Dmf_HingeAngle.cpp, Dmf/Modules.Library/Dmf_MobileBroadband.cpp, Dmf/Modules.Library/Dmf_SimpleOrientation.cpp, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.c, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.h, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.md, Dmf/Modules.Library/Dmf_UdeClient.c, Dmf/Modules.Library/Dmf_UdeClient.h, Dmf/Modules.Library/Dmf_UdeClient.md, Dmf/Modules.Library/Dmf_VirtualHidAmbientColorSensor.h, Dmf/Modules.Library/Dmf_VirtualHidMini.c
1. Correct SAL issues in DMF_ThreadedBufferQueue.
2. Correct issue in DMF_VirtualHidMini that causes legacy devices with no report id to fail in User-mode (but not Kernel -mode).
3. Add DMF_UdeClient Module to make it easier to create virtual USB devices.
4. Correct report id issue in VirtualHidAmbientColorSensor.
5. Correct issues in DMF_HingeAngle and DMF_SimpleOrientation Modules.
6. Add new Method to DMF_AcpiTarget.
NOTE: This PR contains PR fix submitted by *nefarius*.
=> Merge20210226

Dmf/DmfVersion.h, Dmf/Framework/Modules.Core/Dmf_LiveKernelDump.c, Dmf/Framework/Modules.Core/Dmf_LiveKernelDump.h, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_CrashDump.c, Dmf/Modules.Library/Dmf_CrashDump.h, Dmf/Modules.Library/Dmf_CrashDump.md, Dmf/Modules.Library/Dmf_HidTarget.c, DmfSamples/NonPnp1/sys/DmfInterface.c, DmfSamples/NonPnp1/sys/README.md
1. Add support for new Triage Data Dumps.  (Dmf_LiveKernelDump and Dmf_CrashDump). Also, fix a bug in Dmf_CrashDump that caused BSOD if two instances are created.
2. Correct bug in Dmf_Tests_DeviceInterfaceTarget.
3. Remove Remove Cancel path from Dmf_HidTarget since there is a bug in stack . We will revisit this later and possibly add back as an option.
=> Merge20210421

Dmf/DmfVersion.h, Dmf/Framework/DmfCore.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library/Dmf_BufferPool.c, Dmf/Modules.Library/Dmf_BufferQueue.c, Dmf/Modules.Library/Dmf_BufferQueue.h, Dmf/Modules.Library/Dmf_BufferQueue.md, Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_HidTarget.h, Dmf/Modules.Library/Dmf_HidTarget.md, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.c, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.h, Dmf/Modules.Library/Dmf_ThreadedBufferQueue.md
0. Correct bug in Dmf_DveiceInterfceMultipleTarget when underlying target disappears and reappears. (This is an important fix.)
1. Add Method to Dmf_BufferQueue to allow Client to free resources allocated per Client buffer.
2. Update Dmt_ThreadedBufferQueue to give Client access to new Dmf_BufferQueue clean up Method.
3. Correct issues in Dmf_ContinuousRequestTarget when failures occur during Stream Start (now does proper clean up).
4. Correct bug in DMF Core when DMF_Module_OpenOrRegisterNotificationOnCreate() fails.
5. Update unit tests to correct bugs in certain execution scenarios.
6. Update Dmf_HidTarget to support asynchronous Feature Get.
=> Merge20210505

Dmf/DmfVersion.h, Dmf/Framework/DmfCore.c
Fix regression that can cause BSOD in existing Client drivers. The regression was introduced by Release  v1.1.87:
Correct bug in DMF Core when DMF_Module_OpenOrRegisterNotificationOnCreate() fails.
=> Merge20210728

Dmf/DmfVersion.h, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Modules.Library.Tests/Dmf_Tests_ScheduledTask.c, Dmf/Modules.Library/Dmf_ScheduledTask.c, Dmf/Modules.Library/Dmf_ScheduledTask.h, Dmf/Modules.Library/Dmf_ScheduledTask.md, Dmf/Modules.Library/Dmf_Stack.c
Merge20210730
1. Don't delete WWP recorder if not created.
2. Remove context from DMF_ScheduledTask_ExecuteNowDefferedEx() to clean up contract. Legacy version is unchanged.
3. Correct verifier issue caused by DMF_Stack using NonPagedPool instead of NonPagedPoolNx.
=> Merge20210730

Dmf/DmfVersion.h, Dmf/Documentation/Driver Module Framework.md, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Framework/DmfIncludes_USER_MODE.h, Dmf/Framework/DmfUtility.c, Dmf/Modules.Library.Tests/TestsUtility.c, Dmf/Modules.Library/Dmf_BufferPool.c, Dmf/Modules.Library/Dmf_Registry.c, Dmf/Modules.Library/Dmf_Registry.md
1. Correct bug in DMF_BufferPool where system time is used instead of interrupt time. This can cause bugs if user changes system time while Methods that use timers are called (DMF_BufferPool_PutWithTimer()).
2. Add temperature functions.
3. Make clarification in DMF_Registry comments and fix error in documentation for DMF_IsModuleDynamic.
4. Add  macro that checks for latest version of Windows.
=> Merge20210921

Dmf/Modules.Library/Dmf_UdeClient.c
`UdeClient_CreateAndPlugUsbDevice` always assigns the module context values for Port type and number, which will always be zero when `DMF_UdeClient_DeviceInformationGet` is used after device creation.
=> Fixed udeDeviceInformation assignment in UdeClient_CreateAndPlugUsbDevice

Dmf/DmfVersion.h, Dmf/Framework/DmfIncludes.h, Dmf/Modules.Library.Tests/Dmf_Tests_BufferQueue.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library/Dmf_ComponentFirmwareUpdate.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_GpioTarget.c, Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.c, Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.h, Dmf/Modules.Library/Dmf_SpiTarget.c, Dmf/Modules.Library/Dmf_UdeClient.c, Dmf/Modules.Library/Dmf_UdeClient.h, Dmf/Modules.Library/Dmf_UdeClient.md, Dmf/Solution/DmfU/DmfU.vcxproj, Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj, Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters, Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj
Merge20211111
1. Update DMF_UdeClient to correct issues with Manual dispatch type endpoints.
2. Correct bug in DMF_DeviceInterfaceTarget when device interface is disabled. Also, update unit tests to test disable/enable of device interface targets.
3. Add DMF_GpioTarget and DMF_SpiTarget to User-mode Library (they are already in Kernel-mode Library).
4. DMF_USER_MODE is now automatically defined based on UMDF settings. Thus, it is no longer necessary for Client User-mode drivers to define DMF_USER_MODE as it was in the past.
=> Merge20211111

Dmf/Documentation/Driver Module Framework.md, Dmf/Modules.Library/Dmf_ComponentFirmwareUpdate.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
1. Fix BSOD in DMF_DeviceInterfaceMulitpleTarget. It happens when the underlying WDFIOTARGET fails to open during "Remove Cancel" path.
2. Correct issue in DMF_ComponentFirmwareUpdate.c. Strict compiler settings will fail with unused local variables that are set.
3. Update list of contributors in documentation.
=> Merge20211209

Dmf/DmfVersion.h, Dmf/Documentation/Driver Module Framework.md, Dmf/Framework/DmfCall.c, Dmf/Framework/DmfDefinitions.h, Dmf/Modules.Library/Dmf_BufferPool.h, Dmf/Modules.Library/Dmf_BufferQueue.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_QueuedWorkItem.h
1. Add ability for Module authors to set non-zero default values in a Module's Config. DECLARE_DMF_MODULE_EX()
2. Update default Config for DMF_BufferPool, DMF_BufferQueue and DMF_QueuedWorkitem.
3. Allow User-mode Clients of DMF_DeviceInterfaceTarget to fail the Open of a device interface instance.
4. Update the check for Paged Pool type to be simpler.
=> Merge20211217

Dmf/DmfVersion.h, Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Modules.Library/Dmf_AcpiPepDevice.c, Dmf/Modules.Library/Dmf_AcpiPepDevice.h, Dmf/Modules.Library/Dmf_AcpiPepDeviceFan.c, Dmf/Modules.Library/Dmf_AcpiTarget.c, Dmf/Modules.Library/Dmf_AcpiTarget.h, Dmf/Modules.Library/Dmf_AcpiTarget.md, Dmf/Modules.Library/Dmf_CrashDump.c, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_Registry.c
Merge22020222
1. Remove all use of ExAllocatePool() in order to support CodeQl requirements.
2. Correct regression in DMF_AcpiPepDevice.c and DMF_AcpiPepDeviceFan.c caused by  v1.1.15.
=> Merge22020222

Dmf/DmfVersion.h, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Framework/DmfUtility.c, Dmf/Modules.Library/DMF_String.h, Dmf/Modules.Library/DMF_UefiOperation.c, Dmf/Modules.Library/DMF_UefiOperation.h, Dmf/Modules.Library/DMF_UefiOperation.md, Dmf/Modules.Library/Dmf_Doorbell.c, Dmf/Modules.Library/Dmf_NotifyUserWithRequestMultiple.c
1. Correct BSOD regression in DMF_Doorbell where callback was paged but should not be because it can potentially acquire a spinlock.  Regression introduced in v1.1.114.
2. Correct definition names of macros that check for WDK versions.
3. Correct bug in DMF_UefiOperation where Methods did not receive DMFMODULE parameter (benign bug).
4. Add DMF_Utility_SystemTimeCurrentGet()  which is Kernel/User-mode compatible call to get system time.
5. Update DMF_NotifyUserWithRequestMultiple to support caching all buffers in queue, not just a single  (last) buffer.
=> Merge20220308

Dmf/DmfVersion.h, Dmf/Framework/DmfDefinitions.h, Dmf/Framework/DmfUtility.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c, Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler_Public.h, Dmf/Modules.Library/DMF_UefiOperation.c, Dmf/Modules.Library/DMF_UefiOperation.h, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.md, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md, Dmf/Modules.Library/Dmf_File.c, Dmf/Modules.Library/Dmf_File.h, Dmf/Modules.Library/Dmf_File.md, Dmf/Modules.Library/Dmf_NotifyUserWithRequestMultiple.c, Dmf/Modules.Library/Dmf_Rundown.h, Dmf/Modules.Library/Dmf_VirtualHidDeviceVhf.h, Dmf/Modules.Library/Dmf_VirtualHidKeyboard.c
Merge20220512
1. Correct issue with missing ReportId field in DMF_VirtualHidKeyboard.
2. Correct bug in DMF_DeviceInterfaceTarget and DMF_DeviceInterfaceMultipleTarget when Client vetoes QueryRemove.
3. Add example of how to use WdfIoTargetQueryInterface() when using DMF_DeviceInterfaceTarget and DMF_DeviceInterfaceMultipleTarget. (See the corresponding Test Modules.)
4. Update DMF unit tests to test more scenarios such as QueryInterface. Also correct some issues in unit tests.
5. Correct some SAL issues.
6. Remove some duplicate definitions.
7. Correct some comments.
8. Add DMF_File_BufferDecompress() Method.
9. Add DMF_DeviceInterfaceMultipleTarget_Reference() and DMF_DeviceInterfaceMultipleTarget_Deeference() to allow Client to reference individual WDFIOTARGET exposed by the Module.
=> Merge20220512

Dmf/DmfVersion.h, Dmf/Modules.Library/Dmf_IoctlHandler.c, Dmf/Modules.Library/Dmf_IoctlHandler.h, Dmf/Modules.Library/Dmf_IoctlHandler.md, Dmf/Modules.Template/Dmf_NonPnp.c, Dmf/Modules.Template/Dmf_OsrFx2.c
Merge20220719
1. Correct issue related to creating device interface for child PDO. Note: This change updates the Client callback signature. (This fixes the second issue reported in issue #218.)
2. Update documentation to clarify BytesReturned parameter for IOCTL handler callback in DMF_IoctlHandler.
=> Merge20220719

Dmf/DmfVersion.h, Dmf/Framework/DmfGeneric.c, Dmf/Modules.Library/DmfModules.Library.h, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_Time.c, Dmf/Modules.Library/Dmf_Time.h, Dmf/Modules.Library/Dmf_Time.md, Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj, Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
1. Work around issue where WDF sometimes calls QuerRemove callback twice.
2. Fix some asserts.
3. Add DMF_Time Module. More Methods to be added later.
4. During RemoveComplete close WDFIOTARGET before calling Client callback so view is the same as if QueryRemove had happened.
=> Merge20220812

Dmf/DmfVersion.h, Dmf/Solution/DmfU/DmfU.vcxproj, Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj, Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj, Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters, Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj, DmfSamples/VHidMini2Dmf/User/VHidMini2DmfU.vcxproj
Update to enable building using NI EWDK (EWDK_ni_release_svc_prod1_22…621_220804-1759) using Visual Studio 2022.
Also it is necessary to execute this command in EWDK prior to starting Visual Studio: 
`set MSBuildUserExtensionsPath=%VSINSTALLDIR%\MsBuild`
It is anticipated that later versions of the EWDK will not need the extra command.
=> Merge20221103

Dmf/DmfVersion.h, Dmf/Modules.Library/Dmf_BufferPool.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
Merge20221118
1. Fix issue in DMF_BufferPool to enforce that ClientBuffer is 4-byte aligned. Some NT APIs on ARM require 4-byte alignment. When Client buffer is not 4-byte aligned it is possible that elements may not be aligned when they are at the start of buffer.
2. Clear symbolic link on other failure paths in DMF_DeviceInterfaceTarget.
=> Merge20221118

Dmf/Modules.Library/Dmf_CrashDump.c
This change converts hard-linking against `KeInitializeTriageDumpDataArray` and `KeAddTriageDumpDataBlock` (APIs only available since Windows 10 version 1803) into dynamically resolving them at runtime and soft-failing, if not found.
This restores full DMF compatibility again all the way down to Windows 10 version 1507.
=> Restores compatibility with Windows 10 versions below 1803

Dmf/DmfVersion.h, Dmf/Framework/DmfCall.c, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Framework/DmfIncludes_USER_MODE.h, Dmf/Framework/DmfInterfaceInternal.c, Dmf/Framework/DmfInternal.c, Dmf/Framework/DmfLiveKernelDump.c, Dmf/Modules.Library.Tests/Dmf_Tests_SelfTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
Merge20230705
1. Fix memory leak in DMF_DeviceInterfaceMultipleTarget.
2. Reduce the number of WDF handles DMF Core uses to a) reduce memory usage b) reduce chance of warning about many WDF objects possibly indicating a memory leak. (Kernel-mode only).
3. Fix an error in DMF_SelfTarget unit test.
=> Merge20230705

Dmf/DmfVersion.h, Dmf/Framework/DmfCall.c, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfHelpers.c, Dmf/Framework/DmfIncludeInternal.h, Dmf/Framework/DmfModuleCollection.c, Dmf/Framework/DmfUtility.c, Dmf/Framework/DmfValidate.c, Dmf/Modules.Library/Dmf_BufferPool.c, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_HidTarget.h
Merge20230714
1. Fix regression in pre-1809 Windows due to ExAllocatePool2.
2. Track buffers actually used in BufferPool so that better initial preallocation choices can be made.
3. Fix BSOD when Modules are created and memory is not available. (Fault injection/low memory situations.) Also fix associated asserts that failed in this case.
4. Use more tags to make it easier to understand what memory is allocated. (No logical change to algorithm...just additional counters.)
5. Add DMF_HidTarget_HidCollectionInformationGet() to HidTarget Module.
=> Merge20230714

Dmf/DmfVersion.h, Dmf/Modules.Library.Tests/Dmf_Tests_DefaultTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c, Dmf/Modules.Library/DmfModules.Library.h, Dmf/Modules.Library/Dmf_DefaultTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c, Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c, Dmf/Modules.Library/Dmf_HidDeviceListener.c, Dmf/Modules.Library/Dmf_HidDeviceListener.h, Dmf/Modules.Library/Dmf_HidDeviceListener.md, Dmf/Modules.Library/Dmf_HidTarget.c, Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.c, Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.h, Dmf/Modules.Library/Dmf_IoctlHandler.c, Dmf/Modules.Library/Dmf_MobileBroadband.cpp, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c, Dmf/Modules.Library/Dmf_QueuedWorkItem.c, Dmf/Modules.Library/Dmf_ScheduledTask.c
Merge202040409
1. Correct regression in DMF_IoctlHandler when ReferenceString is used. BSOD caused by incorrect use of WdfFileObjectGetFileName().
2. Add DMF_HidDeviceListener. Lets client know when HID devices appear/disappear.
3. Correct DMF_DefaultTarget, DMF_DeviceInterfaceMultipleTarget and DMF_DeviceInterfaceTarget callback chaining. Chaining was not correct because it was not honoring rule that DMFMODULE passed to callback must be from immediate Child Module. Also, make corresponding changes to unit test code, DMF_Tests_DefaultTarget, DMF_Tests_DeviceInterfaceTarget and DMF_Tests_DeviceInterfaceMultipleTarget.
4. Make DMF_MobileBroadband more robust in cases of stress.
5. Clean up logging in DMF_NotifyUserWithRequest.
6. Fix issue in DMF_IoctlHandler when filtering WDFERQUESTS for …
=> Merge202040409

Dmf/DmfVersion.h, Dmf/Framework/DmfCore.c, Dmf/Framework/DmfIncludes_KERNEL_MODE.h, Dmf/Modules.Library.Tests/Dmf_Tests_BufferQueue.c, Dmf/Modules.Library/Dmf_BufferQueue.c, Dmf/Modules.Library/Dmf_BufferQueue.h, Dmf/Modules.Library/Dmf_BufferQueue.md, Dmf/Modules.Library/Dmf_IoctlHandler.c, Dmf/Modules.Library/Dmf_IoctlHandler.h, Dmf/Modules.Library/Dmf_IoctlHandler.md, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.h, Dmf/Modules.Library/Dmf_NotifyUserWithRequest.md
Merge20241212
1. Correct a race condidition in NotifyUserWithRequest. (If a single Request is available but it is completed after it is has started to be populated, the data that could not be put in the request is lost.) It is hard to hit this race condition, but it is possible under stress conditions or when there are very few requests available for incomming data.
1. Add support for loading IoctlHandler dynamically. Now any Module that does not support plug and play WDF callbacks can be loaded dynamically. Previously any Module that supported any WDF callbacks was prevented from loading dynamically.
3. Add DMF_BufferQueue_EnqueueWithTimer() and update unit tests to support it.
=> Merge20241212
