- README.md
Some feedback indicated adding reference to blog would be good.
> Update to add reference to blog post.

- Dmf/Modules.Library/Dmf_AcpiTarget.c
> renmoved outputBuffer = NULL

- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_Transport_ComponentFirmwareUpdate.h
- Dmf/Modules.Library/Dmf_VirtualHidKeyboard.c
- Dmf/Modules.Library/Dmf_VirtualHidKeyboard.h
- Dmf/Modules.Library/Dmf_VirtualHidKeyboard.md
- Dmf/Solution/DmfKFramework/DmfKFramework.vcxproj.filters
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters
- Dmf/Solution/DmfKModules.Template/DmfKModules.Template.vcxproj
- Dmf/Solution/DmfKModules.Template/DmfKModules.Template.vcxproj.filters
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj.filters
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
- Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj
- Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj.filters
1. Add DMF_VirtualHidKeyboard
2. Correct issues project files with .md files.
3. Add Dmf_Transport_ComponentFimrwareupdate in preparation for coming updates.
> Merge 2018052018

- Dmf/Framework/Modules.Core/Dmf_BufferPool.c
- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_GpioTarget.c
- Dmf/Modules.Library/Dmf_GpioTarget.md
- Dmf/Modules.Library/Dmf_HidPortableDeviceButtons.c
- Dmf/Modules.Library/Dmf_HidPortableDeviceButtons.h
- Dmf/Modules.Library/Dmf_SpbTarget.c
- Dmf/Modules.Library/Dmf_SpbTarget.h
- Dmf/Modules.Library/Dmf_SpbTarget.md
- Dmf/Modules.Library/Dmf_VirtualAmbientLightSensor.md
- Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.c
- Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.h
- Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.md
- Dmf/Modules.Library/Dmf_VirtualHidDeviceVhf.h
- DmfSamples/SwitchBar/DmfInterface.c
- DmfSamples/SwitchBar2/DmfInterface.c
- DmfSamples/SwitchBar3/DmfInterface.c
- DmfSamples/SwitchBar4/DmfInterface.c
1. Fix bug in DMF_BufferPool.
2. Fix bug in Samples (SwitchBar1,SwitchBar2,SwitchBar3,SwitchBar4).
3. Add DMF_SpbTarget.
4. Add DMF_VirtualHidAmbientLightSensor.
5. Update DMF_Gpio documentation.
> Merge 20181029

- README.md
Make a single list of Module that has associated summaries.
> Update to remove list of Modules so there is only a single list.

- Dmf.sln
- Dmf/Framework/Modules.Core/Dmf_Bridge.c
- Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c
- Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h
- Dmf/Modules.Library/Dmf_DefaultTarget.c
- Dmf/Modules.Library/Dmf_DefaultTarget.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h
- Dmf/Modules.Library/Dmf_SerialTarget.c
- Dmf/Modules.Library/Dmf_SerialTarget.h
1. Correct SAL for ContinuousRequestTarget_Stop() due to native rundown API's use.
2. Add documentation to solution for easy access.
3. Change few "VOID." to "None".
> Merge20181120

- Dmf/Framework/Modules.Core/Dmf_BufferPool.c
- Dmf/Framework/Modules.Core/Dmf_BufferQueue.c
- Dmf/Framework/Modules.Core/Dmf_BufferQueue.h
- Dmf/Framework/Modules.Core/Dmf_BufferQueue.md
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.md
- Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c
- Dmf/Modules.Library/Dmf_HidTarget.c
- Dmf/Modules.Library/Dmf_HidTarget.h
- Dmf/Modules.Library/Dmf_HidTarget.md
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.h
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.md
- Dmf/Modules.Library/Dmf_RequestTarget.c
- Dmf/Modules.Library/Dmf_SerialTarget.c
- Dmf/Modules.Library/Dmf_String.c
1. Strengthen asserts in BufferPool to prevent improper usage and associated changes.
2. Fix some SAL issues.
3. Add Methods to HidTarget and NotifyUserWithRequest.
4. Some documentation fixes.
5. Update RequestTarget for use with Dynamic Modules.
> Merge20181228

- Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c
- Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c
- Dmf/Modules.Library.Tests/Dmf_Tests_RingBuffer.c
- Dmf/Modules.Library/Dmf_CmApi.c
- DmfSamples/InterfaceSample1/DmfInterface.c
- DmfSamples/LegacyProtocolTransport/DmfInterface.c
- DmfSamples/NonPnp1/sys/DmfInterface.c
- DmfSamples/SwitchBar3/DmfInterface.c
- DmfSamples/SwitchBar4/DmfInterface.c
- DmfSamples/SwitchBar5/DmfInterface.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_1/device.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_1/ioctl.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_1/osrusbfx2.h
- DmfSamples/kmdf_fx2_dmf/driver_dmf_2/device.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_2/ioctl.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_2/osrusbfx2.h
- DmfSamples/kmdf_fx2_dmf/driver_dmf_3/Interrupt.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_3/device.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_4/Interrupt.c
- DmfSamples/kmdf_fx2_dmf/driver_dmf_4/device.c
- DmfTest/DmfKTest/sys/DmfInterface.c
I encountered several SAL issues in samples and framework using VS2019.
This PR corrects them. It is all non-functional changes.
> Correct SAL issues found using VS2019

- Dmf/Framework/DmfCore.c
Correct issue where excessive stack is used which can cause stack overflow easily in x86. Each assert causes stack to grow as the compiler seems to want to remember the result of each assert. Because that function is called recursively it becomes a problem especially on x86.
> Merge20191114

- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.h
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.md
- Dmf/Modules.Library/Dmf_ComponentFirmwareUpdate.c
- Dmf/Modules.Library/Dmf_ComponentFirmwareUpdateHidTransport.c
- Dmf/Modules.Library/Dmf_ComponentFirmwareUpdateHidTransport.h
1. Merge latest CFU updates. These are necessary for updated CFU samples in CFU repository.
2. Correct an issue with DMF_IoctlHandler which was not properly allowing Client to create device interface in a disabled state.
> Merge20191115

- Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c
Fix assert in CHK build of windows due to rundown logic.
> Merge20191118.1

- Dmf/Framework/DmfContainer.c
- Dmf/Framework/DmfCore.c
- Dmf/Framework/DmfGeneric.c
- Dmf/Framework/DmfHelpers.c
- Dmf/Framework/DmfModuleCollection.c
- Dmf/Modules.Library/Dmf_ContinuousRequestTarget.c
- Dmf/Modules.Library/Dmf_Registry.c
- Dmf/Modules.Library/Dmf_ScheduledTask.c
- Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.h
1. Correct error where DMFMODULE type is not set before calling PostOpen() with DynamicModules.
2. Reduce logging to avoid filling log buffers with irrelevant data.
3. Add ACS report data.
> Merge20200127

- Dmf/Framework/DmfCore.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_Rundown.c
Allow Client to access returned Dynamic Module handle address during PostOpen.
> Allow Client to access returned Dynamic Module handle address during PostOpen.

- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
Add rundown support for DMF_NotifyUserWithRequest Methods.
> Merge20200130

- Dmf/Framework/DmfDefinitions.h
- Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c
- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.md
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.md
- Dmf/Modules.Library/Dmf_HingeAngle.cpp
- Dmf/Modules.Library/Dmf_HingeAngle.h
- Dmf/Modules.Library/Dmf_HingeAngle.md
- Dmf/Modules.Library/Dmf_MobileBroadband.cpp
- Dmf/Modules.Library/Dmf_MobileBroadband.h
- Dmf/Modules.Library/Dmf_SimpleOrientation.cpp
- Dmf/Modules.Library/Dmf_SimpleOrientation.h
- Dmf/Modules.Library/Dmf_SimpleOrientation.md
- Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.h
1. Correct issues with User-mode drivers inctroduced in previous update.
2. Give Client access to GUID from DMF_DeviceInterfaceTarget and DMF_DeviceInterfaceMultipleTarget.
> Fix  User-mode issues caused by last commit.

- Dmf/Documentation/Driver Module Framework.md
- Dmf/Modules.Library/Dmf_AlertableSleep.c
- Dmf/Modules.Library/Dmf_AlertableSleep.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
1. Correct issues with DMF_AlertableSleep due to recent changes.
2. Update documentation to explain some DMF related concepts and to remove references to obsolete code.
3. Correct  issues in DMF_DeviceInterfaceTarget and DMF_DeviceInterfaceMultipleTarget related to Query Remove and Remove Cancel.
> Merge20200305

- Dmf/Documentation/Driver Module Framework.md
- Dmf/Framework/DmfDefinitions.h
- Dmf/Framework/DmfIncludeInternal.h
- Dmf/Framework/DmfModuleCollection.c
- Dmf/Framework/DmfUtility.c
- Dmf/Modules.Library.Tests/Dmf_Tests_SelfTarget.c
- Dmf/Modules.Library.Tests/Dmf_Tests_String.c
- Dmf/Modules.Library/Dmf_AlertableSleep.c
- Dmf/Modules.Library/Dmf_Pdo.h
- Dmf/Modules.Library/Dmf_Pdo.md
- Dmf/Modules.Library/Dmf_Registry.c
- DmfTest/DmfKTest/sys/DmfInterface.c
- DmfTest/DmfUTest/sys/DmfInterface.c
Merge20200312
1. Remove excess logging from DMF_Registry.
2. Update  event logging mechanism in Modules to support modern  APIs.
3. Update documentation for new logging API.
4. Correct error in unit test code.
5. Correct some SAL annotations.
6. Update test driver to use updated logging API. tests.
7. Update DMF_Tests_String to unit test logging API.
> Merge20200312

- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
Fix double close call issue caused by QueryRemove path that causes aserts but is benign in practice.
> Merge20200403

- Dmf/Modules.Library.Tests/Dmf_Tests_HashTable.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_QueuedWorkItem.c
- Dmf/Modules.Template/Dmf_SampleInterfaceUpperTransport1.c
- Dmf/Modules.Template/Dmf_SampleInterfaceUpperTransport2.c
- README.md
1. Correct surprise-removal path in DMF_DeviceInterfaceMultipleTarget.c.
2. Convert assert into a run-time check in DMF_QueuedWorkItem.c.
3. Change test so that less CPU is used.
4. Update  readme.md to add feedback email address.
5. Correct SAL issue in sample.
> Merge20200414

- Dmf/Modules.Library/Dmf_HidTarget.c
1. Fix incorrect update to DMF_HidTarget in previous PR.
> Merge20200616.1

- Dmf/Framework/DmfGeneric.c
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.h
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.md
- Dmf/Modules.Library/Dmf_HidTarget.c
- Dmf/Modules.Library/Dmf_HidTarget.h
- Dmf/Modules.Library/Dmf_HidTarget.md
1. Correct failure to check return code in DMF_IoctlHandler.c.
2. Add ability for Client to automatically forward unhandled requests.
3. Remove improper Kernel-mode API in DMF_HidTarget.
4. Correct assert hit with filter drivers.
> Merge20200721

- Dmf/Documentation/Driver Module Framework.md
- Dmf/Framework/DmfCore.c
- Dmf/Framework/DmfIncludeInternal.h
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c
1. Correct bug in IoctlHandler Module that prevent Client driver from seeing Cleanup callback.
2. Correct bug in Dynamic Module creation that required parent device to be a WDFDEVICE instead of a Module when a Module creates a Dynamic Module..
> Merge20208004

- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.h
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.md
1. Add support for ReferenceString when creating device interfaces.
> Merge20200805

- Dmf/Framework/DmfGeneric.c
- Dmf/Framework/DmfInternal.c
- Dmf/Framework/Modules.Core/Dmf_BranchTrack.c
- Dmf/Framework/Modules.Core/Dmf_Bridge.c
- Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c
- Dmf/Modules.Library/Dmf_CrashDump.c
1. Fix mismatched paged code settings that can cause BSOD.
> Merge20200806

- Dmf/Framework/Modules.Core/Dmf_Bridge.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
Correct two more paged code issues found during stress testing.
> Merge20200811

- Dmf/Framework/DmfCore.c
- Dmf/Framework/DmfModuleCollection.c
- Dmf/Modules.Library/Dmf_RequestTarget.c
1. Corrrect paged code issue.
2. Update core to allow easier support for situations where a Module that has no Config  has a Confiig added to it.
> Merge20200826

- Dmf/DmfVersion.h
- Dmf/Documentation/Driver Module Framework.md
1. Update documentation.
2. Add version file so build systems can detect release information.
(Non-functional changes)
> Merge20201102

- Dmf/DmfVersion.h
> Update version file.

- Dmf/DmfVersion.h
- Dmf/Framework/DmfCall.c
- Dmf/Framework/DmfCore.c
- Dmf/Framework/DmfIncludeInternal.h
> Merge20210119

- Dmf/DmfVersion.h
- Dmf/Documentation/Driver Module Framework.md
- Dmf/Framework/DmfCall.c
- Dmf/Framework/DmfModule.h
- Dmf/Framework/Modules.Core/Dmf_IoctlHandler.c
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.h
1. Correct issue in DMF_IoctlHandler when ManualMode is TRUE.
2. Correct PAGED_CODE()/SAL issues in DMF_NotifyUserWithRequest.
3. Prevent invalid Parent/Child ModuleOpen Option combinations.
4. Update documentation to explain Module Open Options in more detail.
> Merge20210129

- Dmf/DmfVersion.h
- Dmf/Framework/DmfModule.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
- Dmf/Modules.Library/Dmf_HidTarget.c
- Dmf/Modules.Library/Dmf_SerialTarget.c
- DmfTest/DmfKTest/sys/Trace.h
- DmfTest/DmfUTest/sys/trace.h
1. Correct bug in Dmf_HidTarget where thread Module is started but not yet created (based on capabilities).
2. Correct issue in Dmf_SerialTarget in Manual Mode.
3. Allow _GuidGet() to be called when Module is not yet opened.
4. Minor changes to Unit Test driver trace.h.
> Merge20210527

- Dmf/DmfVersion.h
- Dmf/Framework/DmfModule.h
- Dmf/Modules.Library/Dmf_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library/Dmf_DeviceInterfaceTarget.c
Fix regression caused by previous PR (v1.1.88).
> Merge20210527.1

- Dmf/DmfVersion.h
- Dmf/Framework/DmfIncludes_KERNEL_MODE.h
- Dmf/Framework/Modules.Core/DmfModules.Core.h
- Dmf/Modules.Library/Dmf_MobileBroadband.cpp
1. Fix two more compilation issues related to recent changes to support existing configurations from users.
2. Update DMF_MobileBroadband.cpp.
> Merge20210610

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_AcpiPepDevice.h
Merge20210610.2
Missed one file in merge of 20210610.
> Merge20210610.2

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_Registry.c
- Dmf/Modules.Library/Dmf_Registry.h
- Dmf/Modules.Library/Dmf_Registry.md
Update  DMF_Registry to clarify issues related to WCOS and add one Method to give consistent access to driver's Parameters key using DMF.
> Merge20210625

- Dmf/DmfVersion.h
- Dmf/Modules.Library/DMF_UefiOperation.c
- Dmf/Modules.Library/DMF_UefiOperation.h
- Dmf/Modules.Library/DMF_UefiOperation.md
- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_AcpiPepDevice.c
- Dmf/Modules.Library/Dmf_AcpiPepDeviceFan.c
- Dmf/Modules.Library/Dmf_AcpiPepDeviceFan.h
- Dmf/Modules.Library/Dmf_AcpiPepDeviceFan.md
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
1. Add new Module: DMF_UefiOperation
2. Update DMF_AcpiPepDevice and DMF_AcpiPepDeviceFan for more flexibility.
> Merge20210701

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_AcpiPepDeviceFan.h
1. Remove unused structure (related to previous PR).
> Merge20210702.1

- Dmf/DmfVersion.h
- Dmf/Modules.Library.Tests/DmfModules.Library.Tests.h
- Dmf/Modules.Library.Tests/Dmf_Tests_Stack.c
- Dmf/Modules.Library.Tests/Dmf_Tests_Stack.h
- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_BufferQueue.c
- Dmf/Modules.Library/Dmf_BufferQueue.h
- Dmf/Modules.Library/Dmf_BufferQueue.md
- Dmf/Modules.Library/Dmf_Stack.c
- Dmf/Modules.Library/Dmf_Stack.h
- Dmf/Modules.Library/Dmf_Stack.md
- Dmf/Solution/DmfKModules.Library.Tests/DmfKModules.Library.Tests.vcxproj
- Dmf/Solution/DmfKModules.Library.Tests/DmfKModules.Library.Tests.vcxproj.filters
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters
- Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj
- Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj.filters
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
- DmfTest/DmfKTest/sys/DmfInterface.c
- DmfTest/DmfUTest/sys/DmfInterface.c
Merge20210713
1. Add DMF_Stack Module and associated unit test Module.
2. Add Method to access buffer context from DMF_BufferQueue..
> Merge20210713

- DmfTest/DmfKTest/sys/DmfInterface.c
- DmfTest/DmfKTest/sys/DmfKTest.rc
- DmfTest/DmfUTest/sys/DmfInterface.c
- DmfTest/DmfUTest/sys/DmfUTest.rc
> Correct crash in DmfUTest when WPP tracing is enabled.

- Dmf/DmfVersion.h
- Dmf/Framework/DmfFilter.c
- Dmf/Framework/DmfLiveKernelDump.c
- Dmf/Framework/Modules.Core/Dmf_LiveKernelDump.c
- Dmf/Modules.Library.Tests/Dmf_Tests_PingPongBuffer.c
- Dmf/Modules.Library.Tests/Dmf_Tests_Registry.c
- Dmf/Modules.Library/Dmf_HidTarget.c
- Dmf/Modules.Library/Dmf_PingPongBuffer.c
- Dmf/Solution/DmfK/DmfK.vcxproj
- Dmf/Solution/DmfKFramework/DmfKFramework.vcxproj
- Dmf/Solution/DmfKModules.Library.Tests/DmfKModules.Library.Tests.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Template/DmfKModules.Template.vcxproj
- Dmf/Solution/DmfU/DmfU.vcxproj
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj
- Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj
Merge20210823
1. Update to correct issues found by static code analyzers. (/lgtm is analyzer syntax for override).
2. Enable PAC linker option for ARM builds for increased security.
> Merge20210823

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_BufferQueue.c
- Dmf/Modules.Library/Dmf_ThreadedBufferQueue.c
Merge20210923
1. Add support for freeing resources allocated in DMF_ThreadedBufferQueue callback.
> Merge20210923

- Dmf/DmfVersion.h
- Dmf/Modules.Library/DmfModules.Library.h
- Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.c
- Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.h
- Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.md
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters
1. Add support for SMF (System Management Framework).
> Merge20211020

- Dmf/DmfVersion.h
Update version number for previous release.
> Merge20211209.1

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_SerialTarget.c
- Dmf/Modules.Library/Dmf_SerialTarget.h
Merge20220118
Correct issue in DMF_SerialTarget where Methods were not reference counting to prevent race condition in case of 1) D0Exit 2) serial target query remove.  This corrects possible BSOD.
> Merge20220118

- Dmf/DmfVersion.h
- Dmf/Framework/DmfIncludes.h
- Dmf/Solution/DmfKFramework/DmfKFramework.vcxproj
- Dmf/Solution/DmfKFramework/DmfKFramework.vcxproj.filters
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj.filters
1. Add DMF_VERSION definition so that Clients can check DMF (release) version.
> Merge20220214

- Dmf/Modules.Library/Dmf_VirtualEyeGaze.c
Updated Dmf_VirtualEyeGaze to include head position and head direction in the report
> Updated Dmf_VirtualEyeGaze to include additional fields

- Dmf/Solution/DmfK/DmfK.vcxproj
- Dmf/Solution/DmfKFramework/DmfKFramework.vcxproj
- Dmf/Solution/DmfKModules.Library.Tests/DmfKModules.Library.Tests.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Template/DmfKModules.Template.vcxproj
- Dmf/Solution/DmfU/DmfU.vcxproj
- Dmf/Solution/DmfUFramework/DmfUFramework.vcxproj
- Dmf/Solution/DmfUModules.Library.Tests/DmfUModules.Library.Tests.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Template/DmfUModules.Template.vcxproj
- DmfTest/DmfKTest/sys/DmfKTest.vcxproj
- DmfTest/DmfUTest/sys/DmfUTest.vcxproj
Non-functional changes to turn on Code Analysis for Release builds. Debug is off since it takes much longer to build and that is what is used for development and testing.
> Turn on code analysis for Release build.

- Dmf/DmfVersion.h
- Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
- Dmf/Modules.Library/Dmf_Pdo.c
- Dmf/Modules.Library/Dmf_Pdo.h
- Dmf/Modules.Library/Dmf_Pdo.md
Merge20220713:
1. Correct DMF_Pdo  issue where child device properties where not written when specified by Client.
2. Update DMF_Tests_Pdo to assign device property.
3. Correct issue in DMF_NotifyUserWithRequest found during stress testing.
> Merge20220713

- Dmf/DmfVersion.h
- Dmf/Modules.Library/DMF_UefiLogs.c
- Dmf/Modules.Library/DMF_UefiOperation.c
Merge20220728
1. Update DMF_UefiLogs to support User-mode.
2. Correct a bug in clean up path in DMF_UefiOperation.
> Merge20220728

- Dmf/DmfVersion.h
- Dmf/Modules.Library/DMF_UefiLogs.c
- Dmf/Modules.Library/Dmf_IoctlHandler.md
Merge20221025
1. Correct issues in DMF_UefiLogs..
2. Documentation correction.
> Merge20221025

- Dmf/DmfVersion.h
Update version number for release. (Previous release was improperly labeled.)
> Merge20221117

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_MobileBroadband.cpp
- Dmf/Modules.Library/Dmf_Pdo.c
Merge20230607
1. Fix issue with custom PDO properties during driver reinstall (DMF_Pdo). Properties were deleted and not added during reinstall.
2. Make  DMF_MobileBroadband more robust.
> Merge20230607

- Dmf/DmfVersion.h
- Dmf/Modules.Library/Dmf_BufferPool.c
- Dmf/Modules.Library/Dmf_MobileBroadband.cpp
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.c
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.h
- Dmf/Modules.Library/Dmf_NotifyUserWithRequest.md
- Dmf/Modules.Library/Dmf_VirtualEyeGaze.c
Merge20230816
1. Add time stamp support to DMF_NotifyUserWithRequest.
2. Ensure that Client buffers are properly aligned in DMF_BufferPool.
3. Correct issue in DMF_MobileBroadband related to Mcc Mnc parsing.
> Merge20230816

- Dmf/DmfVersion.h
- Dmf/Framework/DmfCore.c
- Dmf/Framework/DmfModuleCollection.c
- Dmf/Modules.Library.Tests/Dmf_Tests_BufferPool.c
- Dmf/Modules.Library.Tests/Dmf_Tests_Pdo.c
- Dmf/Modules.Library.Tests/Dmf_Tests_ScheduledTask.c
- Dmf/Modules.Library/Dmf_Interface_SystemManagementFramework.h
- Dmf/Modules.Library/Dmf_QueuedWorkItem.c
- Dmf/Modules.Library/Dmf_QueuedWorkItem.md
Merge20231109
1. Fixes a couple of issues (BSOD) found during low memory stress testing.
2. Correct a documentation issue.
3. Correct a coupule of issues related to CodeQL warnings.
4. Correct some issues found in unit test code.
> Merge20231109

- Dmf/DmfVersion.h
- Dmf/Framework/DmfIncludes_USER_MODE.h
- Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceMultipleTarget.c
- Dmf/Modules.Library.Tests/Dmf_Tests_DeviceInterfaceTarget.c
- Dmf/Modules.Library.Tests/Dmf_Tests_IoctlHandler.c
- Dmf/Modules.Library/DMF_UefiLogs.c
- Dmf/Modules.Library/Dmf_ActivitySensor.cpp
- Dmf/Modules.Library/Dmf_MobileBroadband.cpp
- Dmf/Modules.Library/Dmf_Pdo.c
- Dmf/Modules.Library/Dmf_Pdo.h
- Dmf/Modules.Library/Dmf_Pdo.md
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
1. Add support and example to enable query interface provider to track individual query interface clients. Update unit tests to show example of that support.
2. Make ActivitySensor and MobileBroadband Modules more robust in cases where WinRT API locks up.
3. Update UefiLog to support newer version format.
> Merge20240208

- Dmf/DmfVersion.h
- Dmf/Framework/DmfCall.c
- Dmf/Framework/DmfCore.c
- Dmf/Modules.Library/Dmf_File.c
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj
- Dmf/Solution/DmfKModules.Library/DmfKModules.Library.vcxproj.filters
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj
- Dmf/Solution/DmfUModules.Library/DmfUModules.Library.vcxproj.filters
Merge20240422
1. Correct BSOD that can happen during stress testing when Dynamic Modules are deleted.
2. Fix issue with file sharing when reading a file using DMF_File.
3. Add missing files to .vcxproj files.
> Merge20240422
